### ISSUE TITLE
symlink /kinwin.js -> /dist/kinwin.js

### ISSUE THREAD

**Issue by derhuerst** [aliirz/kinwin.js#2]
By using a [symlink](https://en.wikipedia.org/wiki/Symbolic_link), only one files has to be updated. This helps devs prevent confusion when they change one of the two files.

**Comment by aliirz** [comment]
I removed the extra kinwin.js in 47728f2abf3aeea7245c25fc0e9a22fc43435f78. This was caused because of a bad merge with gh-pages branch. Fixed now. There is only one file to work with inside dist/

Thanks
